// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package server

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	. "github.com/dcm-project/3-tier-demo-service-provider/api/v1alpha1"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List Three-Tier Apps
	// (GET /api/v1alpha1/three-tier-apps)
	ListThreeTierApps(w http.ResponseWriter, r *http.Request, params ListThreeTierAppsParams)
	// Create Three-Tier App
	// (POST /api/v1alpha1/three-tier-apps)
	CreateThreeTierApp(w http.ResponseWriter, r *http.Request, params CreateThreeTierAppParams)
	// Health Check
	// (GET /api/v1alpha1/three-tier-apps/health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Delete Three-Tier App
	// (DELETE /api/v1alpha1/three-tier-apps/{threeTierAppId})
	DeleteThreeTierApp(w http.ResponseWriter, r *http.Request, threeTierAppId string)
	// Get Three-Tier App
	// (GET /api/v1alpha1/three-tier-apps/{threeTierAppId})
	GetThreeTierApp(w http.ResponseWriter, r *http.Request, threeTierAppId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List Three-Tier Apps
// (GET /api/v1alpha1/three-tier-apps)
func (_ Unimplemented) ListThreeTierApps(w http.ResponseWriter, r *http.Request, params ListThreeTierAppsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create Three-Tier App
// (POST /api/v1alpha1/three-tier-apps)
func (_ Unimplemented) CreateThreeTierApp(w http.ResponseWriter, r *http.Request, params CreateThreeTierAppParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health Check
// (GET /api/v1alpha1/three-tier-apps/health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete Three-Tier App
// (DELETE /api/v1alpha1/three-tier-apps/{threeTierAppId})
func (_ Unimplemented) DeleteThreeTierApp(w http.ResponseWriter, r *http.Request, threeTierAppId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Three-Tier App
// (GET /api/v1alpha1/three-tier-apps/{threeTierAppId})
func (_ Unimplemented) GetThreeTierApp(w http.ResponseWriter, r *http.Request, threeTierAppId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListThreeTierApps operation middleware
func (siw *ServerInterfaceWrapper) ListThreeTierApps(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListThreeTierAppsParams

	// ------------- Optional query parameter "max_page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max_page_size", r.URL.Query(), &params.MaxPageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_token", r.URL.Query(), &params.PageToken, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListThreeTierApps(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateThreeTierApp operation middleware
func (siw *ServerInterfaceWrapper) CreateThreeTierApp(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateThreeTierAppParams

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "id", r.URL.Query(), &params.Id, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateThreeTierApp(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteThreeTierApp operation middleware
func (siw *ServerInterfaceWrapper) DeleteThreeTierApp(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "threeTierAppId" -------------
	var threeTierAppId string

	err = runtime.BindStyledParameterWithOptions("simple", "threeTierAppId", chi.URLParam(r, "threeTierAppId"), &threeTierAppId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "threeTierAppId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteThreeTierApp(w, r, threeTierAppId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetThreeTierApp operation middleware
func (siw *ServerInterfaceWrapper) GetThreeTierApp(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "threeTierAppId" -------------
	var threeTierAppId string

	err = runtime.BindStyledParameterWithOptions("simple", "threeTierAppId", chi.URLParam(r, "threeTierAppId"), &threeTierAppId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "threeTierAppId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetThreeTierApp(w, r, threeTierAppId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1alpha1/three-tier-apps", wrapper.ListThreeTierApps)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1alpha1/three-tier-apps", wrapper.CreateThreeTierApp)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1alpha1/three-tier-apps/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1alpha1/three-tier-apps/{threeTierAppId}", wrapper.DeleteThreeTierApp)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1alpha1/three-tier-apps/{threeTierAppId}", wrapper.GetThreeTierApp)
	})

	return r
}

type ListThreeTierAppsRequestObject struct {
	Params ListThreeTierAppsParams
}

type ListThreeTierAppsResponseObject interface {
	VisitListThreeTierAppsResponse(w http.ResponseWriter) error
}

type ListThreeTierApps200JSONResponse ThreeTierAppList

func (response ListThreeTierApps200JSONResponse) VisitListThreeTierAppsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListThreeTierApps400ApplicationProblemPlusJSONResponse Error

func (response ListThreeTierApps400ApplicationProblemPlusJSONResponse) VisitListThreeTierAppsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListThreeTierApps500ApplicationProblemPlusJSONResponse Error

func (response ListThreeTierApps500ApplicationProblemPlusJSONResponse) VisitListThreeTierAppsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateThreeTierAppRequestObject struct {
	Params CreateThreeTierAppParams
	Body   *CreateThreeTierAppJSONRequestBody
}

type CreateThreeTierAppResponseObject interface {
	VisitCreateThreeTierAppResponse(w http.ResponseWriter) error
}

type CreateThreeTierApp201JSONResponse ThreeTierApp

func (response CreateThreeTierApp201JSONResponse) VisitCreateThreeTierAppResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateThreeTierApp400ApplicationProblemPlusJSONResponse Error

func (response CreateThreeTierApp400ApplicationProblemPlusJSONResponse) VisitCreateThreeTierAppResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateThreeTierApp409ApplicationProblemPlusJSONResponse Error

func (response CreateThreeTierApp409ApplicationProblemPlusJSONResponse) VisitCreateThreeTierAppResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateThreeTierApp500ApplicationProblemPlusJSONResponse Error

func (response CreateThreeTierApp500ApplicationProblemPlusJSONResponse) VisitCreateThreeTierAppResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteThreeTierAppRequestObject struct {
	ThreeTierAppId string `json:"threeTierAppId"`
}

type DeleteThreeTierAppResponseObject interface {
	VisitDeleteThreeTierAppResponse(w http.ResponseWriter) error
}

type DeleteThreeTierApp204Response struct {
}

func (response DeleteThreeTierApp204Response) VisitDeleteThreeTierAppResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteThreeTierApp404ApplicationProblemPlusJSONResponse Error

func (response DeleteThreeTierApp404ApplicationProblemPlusJSONResponse) VisitDeleteThreeTierAppResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteThreeTierApp500ApplicationProblemPlusJSONResponse Error

func (response DeleteThreeTierApp500ApplicationProblemPlusJSONResponse) VisitDeleteThreeTierAppResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetThreeTierAppRequestObject struct {
	ThreeTierAppId string `json:"threeTierAppId"`
}

type GetThreeTierAppResponseObject interface {
	VisitGetThreeTierAppResponse(w http.ResponseWriter) error
}

type GetThreeTierApp200JSONResponse ThreeTierApp

func (response GetThreeTierApp200JSONResponse) VisitGetThreeTierAppResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetThreeTierApp404ApplicationProblemPlusJSONResponse Error

func (response GetThreeTierApp404ApplicationProblemPlusJSONResponse) VisitGetThreeTierAppResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetThreeTierApp500ApplicationProblemPlusJSONResponse Error

func (response GetThreeTierApp500ApplicationProblemPlusJSONResponse) VisitGetThreeTierAppResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List Three-Tier Apps
	// (GET /api/v1alpha1/three-tier-apps)
	ListThreeTierApps(ctx context.Context, request ListThreeTierAppsRequestObject) (ListThreeTierAppsResponseObject, error)
	// Create Three-Tier App
	// (POST /api/v1alpha1/three-tier-apps)
	CreateThreeTierApp(ctx context.Context, request CreateThreeTierAppRequestObject) (CreateThreeTierAppResponseObject, error)
	// Health Check
	// (GET /api/v1alpha1/three-tier-apps/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Delete Three-Tier App
	// (DELETE /api/v1alpha1/three-tier-apps/{threeTierAppId})
	DeleteThreeTierApp(ctx context.Context, request DeleteThreeTierAppRequestObject) (DeleteThreeTierAppResponseObject, error)
	// Get Three-Tier App
	// (GET /api/v1alpha1/three-tier-apps/{threeTierAppId})
	GetThreeTierApp(ctx context.Context, request GetThreeTierAppRequestObject) (GetThreeTierAppResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListThreeTierApps operation middleware
func (sh *strictHandler) ListThreeTierApps(w http.ResponseWriter, r *http.Request, params ListThreeTierAppsParams) {
	var request ListThreeTierAppsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListThreeTierApps(ctx, request.(ListThreeTierAppsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListThreeTierApps")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListThreeTierAppsResponseObject); ok {
		if err := validResponse.VisitListThreeTierAppsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateThreeTierApp operation middleware
func (sh *strictHandler) CreateThreeTierApp(w http.ResponseWriter, r *http.Request, params CreateThreeTierAppParams) {
	var request CreateThreeTierAppRequestObject

	request.Params = params

	var body CreateThreeTierAppJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateThreeTierApp(ctx, request.(CreateThreeTierAppRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateThreeTierApp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateThreeTierAppResponseObject); ok {
		if err := validResponse.VisitCreateThreeTierAppResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteThreeTierApp operation middleware
func (sh *strictHandler) DeleteThreeTierApp(w http.ResponseWriter, r *http.Request, threeTierAppId string) {
	var request DeleteThreeTierAppRequestObject

	request.ThreeTierAppId = threeTierAppId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteThreeTierApp(ctx, request.(DeleteThreeTierAppRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteThreeTierApp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteThreeTierAppResponseObject); ok {
		if err := validResponse.VisitDeleteThreeTierAppResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetThreeTierApp operation middleware
func (sh *strictHandler) GetThreeTierApp(w http.ResponseWriter, r *http.Request, threeTierAppId string) {
	var request GetThreeTierAppRequestObject

	request.ThreeTierAppId = threeTierAppId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetThreeTierApp(ctx, request.(GetThreeTierAppRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetThreeTierApp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetThreeTierAppResponseObject); ok {
		if err := validResponse.VisitGetThreeTierAppResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
