// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZ3XPbNhL/V3ZwfbCvJCXFidvqHm4cW2004zoaf0wfIp8LkSsJDQkgABhZzeh/v8EH",
	"JVKUZeXa5Hoz90aRAHaxH7/97eoTSUUhBUduNOl/IjqdY0Hd45mUtwzVjcTU/sxQp4pJwwQnffsxZym1",
	"v8AwVAncadTw9nwIrKAzTEhEpBISlWHojpsbIx+kUKZ92EixgqolvLm9HYFdAmaOQGsicqYNcg2CJ2N+",
	"pzGDydItWuDEyQepxOMSjICpUAuqMjCKTqcsTeACp7TMjbYfv+9+303GnEQEH2khcyR9+yoiBX1kRVmQ",
	"/umrVyevIlIw7n/3ImKWEkmfMG5whoqsIuKu2L7H+vagcIoKeYpWne3bJHXxJBPpe1QJEx0tFeOzVBRF",
	"yZlZht/xVNECF0K9jyWaNGecpf3TpJe8IGvVtLErrWYcjV1qdftG4ZT0yd86Gw93gns71rFXYelqFRGF",
	"H0qmMCP9d+Fy9+vDxeQ3TI09/FxwQxlHNQpupFnG7I1oPqr52qgSt72fVlvXIfCHHPCRaTZhOTPLthfe",
	"iAWYOdM+kpgGfJTChowRkAquywKVTsY8Bi449mEUlnFh1ktFaTTL0HlurbqNsRS1tlutLorTvA+Dzel2",
	"9VxoA0JBmpfaoILgELsHH6s910jTOZ3kCFMlioY0u78TNvtA5dYK74hVlkSkEuxiKDze1+OptmArOrb8",
	"vOWShlF3ef+CGjqhGp8GhWpFHRHoRBtFUwMsQ27YlKHScIR8xjhG8BGVZoIfg+D5MhnzmxEUVGrw378N",
	"n61tN7l1hMksASm0mSnU3/ZOIR6X3e4JwiaVcjZRVC071ap+7/TY530zLL2cPTfxC+CoOiiCYqk/5MfN",
	"HK6+/lkZGZFw8+c1Cwub+vROn/V+uPlG0i6XD5QSqq3D9Y/n8N333e9sQkxyLCBDQ1muW+b17+1TyyyM",
	"a0N56mw/FaqghvRJqVi8hs5dxtSGmlI39jBuTmpQWAMJw0yOO4X7F4cL3rKd+1qdv8tub5DmZr4Dmtx7",
	"CLfYtpakfs/Gj3N/jpVOs7c8X1bguscw+yVun73cZeXKPJvFZq4QY5vWcYaFiLVMsrSwmbZW8UlbPqP7",
	"bttuTGSN0rJxRB5jijJWqEWpfBRJaizyaXtK0Oo+IjIvFc3X97VHasZnORprH6+RfVHmVNUtHuQ9e3Gr",
	"/61dZBP4TMq2C07cdksA4GiBk8g+RZBNjhM4V0iNZQvu/hq0xPQfwDJfFj6UqJYgqaJFBAUamlFDE04L",
	"jGyF0ag+ooK7u+FFm22l7uQHw4pmoGfU2OsUeEhQsax9mzvOPpSOzsDwAo68EvEMOSpqMGjeUPbYe9H6",
	"hvTJv97R+Pdu/MP9UXiI7z91o9Peqnp//M9vDtGtEvEsrtZ883O1ZxWtk20L2UI8gf3cvt3xIZpJJT6y",
	"DNXDnAVSvY8mtbDDymQpPlRJ2FTwxn8F+xWOilIbmFjisI5SKqWL1OMaddjxuZZSNRAJVf0gezoK0EAe",
	"mudvp6T/7nCH3Pi9q/tts64iUsrsj0fwAicPyDMpGN/Rd9xdX1pqoSwba3QTEUghy9wF9GKOHChfszcY",
	"jixbpB8pyy2FG3NPSASHtxL5zZxNDSyYmQOFS0Gz1zS3dU4dJ3DFcn+co5WBIGYCHfccc6o1m7VkHZUa",
	"4df35QRTkztOG4cW51ewRRRpFqjN5wGtc/ZnA2szlHTnk3vxYF88UCkfWLZqoO7WetIA2+bHQ0B3a8c2",
	"+F4y7dzcxEKOj+ZB0hk+GPEe+W5G0LiG28YMFvpz4GVTOglVii6deq383glILZ1zOsF8D3g8SWpqkiz4",
	"Nst4sdz0kMT1XJfIZxYIT09cy1X97D0B2XF4+nsTrfdHmtPj/hlT3DxBYM5mM4Uzl4keaUBMXf5symoN",
	"6UaDq4vh1U8kItd3V1f+6cez4eXggkTkYnA5uB1c7IS+Jqy1tLhdxx1oo8rUlArhKAtcPJT0BU6OW4WY",
	"ekqwL4bqg5ZVRKpTn9vW6sc83j237RecbHZseWotOiLerva8nZ6rdSut2LUYdXgGNYcKB6VQ/QotV/0S",
	"MPz5idR/MMWxBcKTgqeGOFXnadurxz7Npe+yvuagZuXaq6lYz11SB4oeDsjF+c8wUiKgfakcNzZG6n6n",
	"M2NmXk6SVBSdLC1i6Zd1TupY7AlIXLEcF7HNDvX8ZwiroFrlDBgytkmCwZ5qf+lkzM8Go9gaIWeUG7ge",
	"3NzC2Wjoq1vOUuQ+K8JNziRN5wgvkm7rIovFIqHucyLUrBP26s7l8HxwdTOIXyTdZG6KvNYmkpPYGhsu",
	"rD4VzRpV+p+NhrVeuU96STfp2t1CIqeS2f1JN3kZOhYXXx0qWedjj+ZyTnud7UrY/0RmuIOU2BpWmWpt",
	"G08ohPSFACSdMe5micRpoNzzMAvb67jqeyhFCzSotGNnzIpxzQWpioQtBb5Eava7679c/Hnt3PiU9F91",
	"o3bXvR7b9brd/UO7VbRbcq0w18VulxRHEbUU1o32+4tut4pv9NyuNmHt/Kb97GRz3qFF3FEIl0JbxLtM",
	"U9TauvzlXtFhJvLt56ngJy075L6mmesPUTvoe/U1ZQ/DKLFqNTEsjIgui4KqZRWuvjy69AkhZ+jM8cVm",
	"KN7b9kjoHVEfOmEKHBfb0Q9HF6+bJbYZ8n5vg4m1Yn4L4qtESnOG3MSWC7Mpw8z2tBXWbxLWyk5gOHUj",
	"4gBpWTTmdlUwzYLlOVR9IlDflcMvluxPhJk3O2KgPLNdPlV2v4nGnGW2p3DnGaEwg2o8BixLxnzMrz3u",
	"F9ZxcCStoQejuPfixXF/zGPoxacnkM6poqm9MuSCz+z7G0PVuhvJxQJVSjVCjpbbgVCQsRkzdmUow24Q",
	"21qpI+BlMXEPVvf5Us6Ru0H4gGf+/M2ZfqkD7V0Jz7JGon8+Cd03N9gJGy57Xots+UUQw2fOpjCH/nUL",
	"rXpfUPaTXNUmj58EZf9t4HrZ/eHryT4XfJqz9K+JmAHqmpi5BzJX0X4mUU0inyIU12hKxT26zOvj4KqT",
	"CmSthas/oXmzGUB/odr7phqjtitu4GBMQzWrbhoyzLbP55i+r9kvnHiA4fzwIph6mK287XI0u/4Rcu+B",
	"NvvOpsH8mv2FyCGiGz6uAbGpBdnGkjpY/jl42HDly6fuGiDj5dfLnithYCpKnv0l8zZEwMF5G+1Ox5/Q",
	"NKIIJksYXuxKvv+xQOp+tQrX4OL/j88QnzawDi8q4Z+G3fx4Xyu87rU7bm4fBDzxv2MasDkEaAX20Z7/",
	"yHI2xXSZ5rjZ1lR+db/6dwAAAP//at7i3rYkAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
