// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZX3PbNhL/KhhcH+wLSUlx4qZ6uXEsNdGM42hiZ/oQ61yIXEloSAABQMtqRt/9Bn9I",
	"8Z8t5dr4ejN9o8gFdrH729/uQl9xzDPBGTCt8PArVvEKMmIfz4S4piCvBMTmZwIqllRoyhkemo8pjYn5",
	"hTQFGaGPChR6fz5BNCNLiHCAheQCpKZgt1tpLW4Fl7q92VTSjMgNent9PUVGBOkVIFJRkVKlgSnEWXTD",
	"PipI0HxjhdYwt/qRkPx+gzRHCy7XRCZIS7JY0DhCI1iQPNXKfHzVf9WPbhgOMNyTTKSAh+ZVgDNyT7M8",
	"w8PTly9PXgY4o8z9HgRYbwTgIaZMwxIk3gbYHrF9jvL0SMICJLAYjDnN00RV9Tjh8WeQEeU9JSRly5hn",
	"Wc6o3vjf4UKSDNZcfg4F6DiljMbD02gQPcelaUobSWMZA21EjW0/SFjgIf5Hbxfhng9vzwT20otutwGW",
	"8CWnEhI8/OQPNys35/PfINZm83PONKEM5NSHkSQJNSci6bQSay1zaEY/LpaWEPhDAbijis5pSvWmHYW3",
	"fI30iiqHJKoQ3AtuIKM5ijlTeQZSRTcsRIwzGKKpF2Ncl6I814omYCNXmm4wFoNSZqmxRTKSDtF4t7uR",
	"XnGlEZcoTnOlQSIfELMG7os1H4DEKzJPAS0kz2razPqeX+yAyowXPmFjLA5wodhiyD/OqniqCDTQ0Yhz",
	"IyQ1p3ZFf0Q0mRMFD5NCIVFlBDJXWpJYI5oA03RBQSp0BGxJGQToDqSinB0jztJNdMOupigjQiH3/Zn/",
	"bHy7y60jiJYRElzppQT1bHCKwpu83z8BtEullM4lkZteITUcnB67vK/D0ul55CROAB0VGwUo26gv6XE9",
	"h4uvf1ZGBtiffL9lXrBuz+B0b/T9yXeaukI+lpLLtg0ffj5HP77q/2gSYp5ChhLQhKaq5V733jy13EKZ",
	"0oTF1vcLLjOi8RDnkoYldXY5U2mic1VbQ5k+qVBhhSQ01Sl0KncvDlfc8J39Wuzf5be3QFK96qAm+x75",
	"UzS9JYhbs4vjyu1jtJPkPUs3Bbl2Oga6Fm+63FicfyesVxIgNHkbJpDxUIkoiTOTSqUNDzprj3HdznMG",
	"B+7QLR8G+D4kIEIJiufSoUQQbZhNmU28UbMAizSXJC2Pa7yqKFumoI3HnUHmRZ4SWfWo17f33Mb8ayNk",
	"EvRMiI5WCJ3YDZDZwNR5dLSGeWCeApTMj1txjiUQDbeaZnUQJkQbUzI4JOA0aVvykdEvuW010GSEjhTI",
	"O5DhEhhIoiFxxSYDTRKiScRIBscuAsaveIj//YmEv/fDn2ZH/iGcfe0Hp4Nt8f74Xz8cYluhYi/nVfz6",
	"rlizDcpEaLCOxwIyn9unOz7EMiH5HU1A3q6ob3gfa2FaeW100hhui/ypG3jlviLzFR1ludJoboq6BBNs",
	"kLdEiFsDkuNKWe/4XEmHSoL7inuQP215rtElSdP3Czz8dHhArtza7azp1m2Ac5H8cQSvYX4LLBGcso6Z",
	"4OOHC1P2pemUap1+gAQXeWoBvV4BQ4SVnRWaTE0nR+4ITU17dcNcs8AZei+AXa3oQqM11StE0AUnyWuS",
	"mhokjyN0SVO3nW35fPOWcLB94Q0jStFlS9dRrgD9+jmfQ6xT22+Gfvz4FZkCByTxbce3cWSZQD7u38yP",
	"FVojQqje1wbMaLKtkWdDHtc4s/7xEO5srGhy6AVVNuJ1WmRwr28FWcKt5p+BdRfu2jHsMqohU9/CNLsC",
	"iImUZGPNa6V6Jze1bE7JHNJHeOTB3qOiyfBwvRhnm92oh+1odAFsaTjx9MRORsXPwQPsHfqnf9aJ+3HQ",
	"WTtme1xxVTJKowgulxKWNikd6SC+sKnka6MDTkF60/HlaHL5Bgf4w8fLS/f089nkYjzCAR6NL8bX41En",
	"C9YZrmXFdYk7pLTMY51LQEeJb5l9SV5DR00mrrI/hqHqfcg2wMWu+5a1xiZHffuW/QLz3YpGpErVAXZ+",
	"Nft1Rq4yVLSwa+jq8Ayqz/4HpVD1CK1Q/eLpfP/F0X9x2WJqhesPHrprKQZEMwXdD0kq3DD0lPcpWzsF",
	"LXh5PRJbUnR0gEfn79BUcs/2ubQtrtZCDXu9JdWrfB7FPOslcRYKJ9Y7qXKx60XCouGxiK0PkufvkJdC",
	"hZR1oM/YehNbNrcqumFn42lonJBSwjT6ML66RmfTiSt0KY2BuazwJzkTJF4Beh71WwdZr9cRsZ8jLpc9",
	"v1b1Libn48urcfg86kcrnaWVaQ6fhMbZaGTsKTquaWH/2XRSGWmHeBD1o75ZzQUwIqhZH/WjF37wsPgq",
	"Ov3hV7wE3dV36lwy5W5nqgNcQXHei9hqkfaKb5LgIX4D+u1ugFOCm7OZ/Z/3+0XQwfU+ldvB3m/Kzf0O",
	"W/uQ97YYU1oBLpxDFSpGQSOk8iwjcrObRs9XEH822CdL2zv4HWdGuNdsDB5ykinpzTlIuVaLC1cXkSBL",
	"yuwZW64yy6tlxg7HRJIMNEhl+1Zq1HzJQZqJ1kMrI/euY1D0dztUli5L3KUvHr7sB+27gvKycdDvP37V",
	"uA26NVf6lKraZoWdfcfItzqqLgzkcQxKmQx48ahqf5Pz7NtMcPdDHXpfkwQZDgRlK8HLp9Q98RegvgIg",
	"8IJV6Fu4um7BsomHXJECdSjOzODIVQfqz+0kjwhisG7fAoxe1zuOOuTd2lpj2sJ8o+IVieQHfEPWNIFM",
	"cONVZK8VXHJ1IZYmNaR+89TfCW0b4dc82XwXVLvo7mqpnz4bGTX4jrofbC9NCNw9TvK/Tq4X/Z+eTvc5",
	"Z4uUxn/NrPbpWM/rR9K6o8D5SdkLTZKtS/oUdNe/BPY9IvUhp57mTubxNLfpai+9ymytW4GbWfDnZ3It",
	"pV48dFYP9hdPF/dLrtGC5yz5SyLOI+BgxAXd3dMb0DUUofkGTUZdDeX/GZD6T8bNtU7nb3x6fBpgHU6H",
	"/oa7u/s4m07Q3YCkYkUG5SDXI4L2yrcGAH7zB/75iv2s4cFZDC9BU7ySCildQLyJU9gtqxu+nW3/EwAA",
	"///lHE1mxiIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
