// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZ33PbNhL+VzC4PthXkqLixE31cuPYaqIZx9XEyfQh8XkgckWhJgEYACOrHv3vN/hB",
	"ihQpS5lLfb2be5OJH7vY/fbDt/AjTnghOAOmFR49YpUsoCD255kQHynIawGJ+TMFlUgqNOUMj8xgThNi",
	"/kKagozQJwUK/Xo+QbQgGUQ4wEJyAVJTsNvZz92N6hVIwhwksATQnEukF4DIxojZDx5IIXLAI5zy5A5k",
	"RPlACUlZlvCiKBnVK/93OJekgCWXd6EAneSU0WR0Gg2jFzjAeiXMHkqbmXgdYAbaTDW+/SBhjkf4b4NN",
	"VAY+JAMTjCs/db0OsIT7kkpI8eizP9xNvTmf/Q6JNpufc6YJZSCnXGpjoh2VpBq+FX68PuXr+HUc4II8",
	"0KIs8Oj01auTVwEuKHN/D2tjlGnIQHac2tq71zsJRMO1JsndB7gvQeluhvwAmvF0ZVOTmEWUZYigk9Ak",
	"3ySqk+8CNEmJJvvCao2/ryavAyyIXvR5oXgpE0BmGB0pkF9BhhkwkERDeozN2Un6K8tXeKRlCT2JFpJ/",
	"pSnI2wX1cCdpSo0Bkk8bzreWb4JlbNIEbt3AtoPXbhSZUXRUlCZigPRCAtyaIN0SIW5TKLhxFZhJ4Wfc",
	"M9zI08Zz5YvwSXyaveqK3QaD3SHYZKWDhgA/hAREKH2gLVaJ1iCZql216Q6JEGrwuOU7TddmU5GXkuR4",
	"tD0fB1hRlpU5kZ3BTVE2vptYhEpEaVKYQt9aYY53QTSZEQW7Waqa0aQoMlNakkQjmgLTdE5BKnQELKMM",
	"AvQVpKKcHSPO8lX0hV1PUUGEQm78Rz+MNN9QHTqCKIuQ4EpnEtSPw1MUfinj+ATQhqdyOpNErgbVrNHw",
	"9Dj6wjpV4+w8cRI3AR1VGwWoWKn7/LhNkNXo96K7APuT7/fMT2z7MzzterIFUH/yjaU+vhpLyWUPOfxy",
	"jn56Hf+EhOSzHAqUgiY0V53wuu/mVycslClNmMP9nMuCaDzCpaRhfS/1BVNpokvVWkOZPmncMzU7B1hT",
	"nUOv8YpSDjW8FTs7Wu3fF7d3QPI+VnXfkT/FdrQqJt7kceH2OYBrzZbQt3jVF8bq/JvJu5mg9mFnsPY4",
	"1x8857C/fr6ZHb1TTQJ0nyriy0GbiDuHGkxYn2YvA/qZxn17Z/aIsuo+NivNpYyOljALzK8ApbPjToLt",
	"TW44vGijLyXa+FDAIZmmadeTT4zel2BwldyhyYULqwkWHuF/fibhH3H4882R/xHePMbB6XBdfT/+xw8H",
	"3eb7dcJBQP32q7VZ9nulzbWbug5wKdJ/N9r9l7r35n/gSrcRu6SqRykzeNC3gmRwq/kdsF4atXhz3YaG",
	"4rD8bOgHEynJyvrRIdC2Su04l5MZ5E8oyp2U3zDBSLHFgcVq075g2wpcAssM6k9PbCdQ/TncUV+h//X3",
	"dmk9DSrrx82uGFzXyN/iniyTkBkp7m8TxOe2ifOUZFPTUL7T8dXF5OotDvCHT1dX7tcvZ5PLsSGLi/Hl",
	"+OP4olcKt2ux48fHGlRIaVkmupSAjlIvUjwXLqGHDA0G9wCm2RKvA1ztum9ZR6iuA7yE2b5lv8Fsp5yv",
	"TQfYVZvZry9pTRnXga3pCw8vl3Yre1DZNI/QSdVvMPvz3g6WMEOuSdz1dFBJcqM7H0YkF05+PufzwNrq",
	"zjmvXwISS3yOCfDF+Xs0ldxTeSmtqNBaqNFgkFG9KGdRwotBmhShcNMGJ02idQ1pWHW9FrFt6X7+HvlZ",
	"qJplA+hrtq0enKpwFBt9YWfjaWjCkFPCNPowvv6IzqYT19PkNAHm6sKf5UyQZAHoRRR3jrJcLiNihyMu",
	"s4FfqwaXk/Px1fU4fBHF0UIXeUNB45PQhBtdGI+qxntaneBsOmm0ESM8jOIoNqu5AEYENeujOHrpxZ5F",
	"WKWuRo84g95HEF1Kpiy0Fk3RXNGcjyO2VqR9s5qkeITfgn63Ec1KcHM2s/+LOK7SDkx7Aqqeuwa/K9dr",
	"OXTtw967Shp2UlwFhypUyW8zSZVFQeRq0wGcL8DSsyaZlQZ+xxszebB97+8Kkrm4tyWoQkuqF4gLdyki",
	"QTLK7Bk7oTLLa3Y/cwJDEEkK0CCNV4+YGjP3JUjTRXhoFeTB6QJF/7BCvg5ZCnNS5hqPXsVBtz+rX9aG",
	"cbzvXa3fckONNM1uX683f2LmN4KpL/llkoCy2vPlkzZ92/zjt9l2zXiP3TckRdI/J64D/Oo5bU+YkUEk",
	"9+SPwE9sYt7i1AkFSyMeaxX22xi8Ma0G73sYdY+niCAGy27ndfGmLTbaWHdrm5a6YN+67KoKqpoqy9Q0",
	"hUJwE1f/LGvrqg+sNG2B9Jv7sV5U2xy/4enquwG650V63b5OTWO07pTU8PuWVG852cC7njn9TxfVy/jn",
	"57N9ztk8p8lfs5p9Gbbr+Yly7rnRfOfrJ03StSv2HHTfU6z9vv3Pj3Z5uzlPl7ctUv9K4Wu07QXeRv33",
	"r99WCb3cdVYP9pfPl/crrtGclyz9SyLOI+BgxAX9cukt6BaK0Gzl3so6CvK/DEjxM3BxU9r8H5gemAZR",
	"h/Og/5dmv9w4m07Q1yHJxYIM65ZtQAQd1F9N5v3mO/6vkPiuwqOyalOC7emNGsjpHJJVksNmWdvx9c36",
	"XwEAAP//jAXTLrUgAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
