// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"time"
)

// Defines values for ThreeTierAppServiceType.
const (
	ThreeTierAppDemo ThreeTierAppServiceType = "three_tier_app_demo"
)

// Defines values for ThreeTierAppStatus.
const (
	DELETED ThreeTierAppStatus = "DELETED"
	FAILED  ThreeTierAppStatus = "FAILED"
	PENDING ThreeTierAppStatus = "PENDING"
	RUNNING ThreeTierAppStatus = "RUNNING"
)

// AppTierSpec Application tier. Uses OCI image.
type AppTierSpec struct {
	// Image OCI image reference for the application.
	Image   string       `json:"image"`
	Network *TierNetwork `json:"network,omitempty"`
}

// ContainerPort defines model for ContainerPort.
type ContainerPort struct {
	ContainerPort int `json:"container_port"`
}

// DatabaseTierSpec Database tier. Uses abstract identifiers (engine, version) only.
// SP maps engine+version to OCI image (e.g. postgres+16 -> docker.io/library/postgres:16).
type DatabaseTierSpec struct {
	// Engine Database engine (postgres, mysql).
	Engine  string       `json:"engine"`
	Network *TierNetwork `json:"network,omitempty"`

	// Version Database engine version.
	Version string `json:"version"`
}

// Error RFC 7807 problem details
type Error struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   *int32  `json:"status,omitempty"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// Health Health status
type Health struct {
	Path  *string `json:"path,omitempty"`
	State string  `json:"state"`
	Type  *string `json:"type,omitempty"`
}

// ThreeTierApp A 3-tier demo app (web, app, db)
type ThreeTierApp struct {
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Id Unique app ID (server-generated from metadata.name)
	Id       *string              `json:"id,omitempty"`
	Metadata ThreeTierAppMetadata `json:"metadata"`

	// Path Resource path (server-generated)
	Path          *string                 `json:"path,omitempty"`
	ProviderHints *map[string]interface{} `json:"provider_hints,omitempty"`

	// ServiceType Service type (must be three_tier_app_demo)
	ServiceType *ThreeTierAppServiceType `json:"service_type,omitempty"`

	// Spec Three-tier structure (database, app, web)
	Spec       ThreeTierSpec       `json:"spec"`
	Status     *ThreeTierAppStatus `json:"status,omitempty"`
	UpdateTime *time.Time          `json:"update_time,omitempty"`

	// WebEndpoint URL to reach the web tier, populated when an external IP is available
	// (e.g. on OpenShift with a LoadBalancer). Nil when the cluster does not
	// assign an external IP (use `kubectl port-forward` instead).
	WebEndpoint *string `json:"web_endpoint,omitempty"`
}

// ThreeTierAppServiceType Service type (must be three_tier_app_demo)
type ThreeTierAppServiceType string

// ThreeTierAppList defines model for ThreeTierAppList.
type ThreeTierAppList struct {
	NextPageToken *string         `json:"next_page_token,omitempty"`
	ThreeTierApps *[]ThreeTierApp `json:"three_tier_apps,omitempty"`
}

// ThreeTierAppMetadata defines model for ThreeTierAppMetadata.
type ThreeTierAppMetadata struct {
	Labels *map[string]string `json:"labels,omitempty"`
	Name   string             `json:"name"`
}

// ThreeTierAppStatus Aggregated status of the 3-tier app
type ThreeTierAppStatus string

// ThreeTierSpec Three-tier structure (database, app, web)
type ThreeTierSpec struct {
	// App Application tier. Uses OCI image.
	App AppTierSpec `json:"app"`

	// Database Database tier. Uses abstract identifiers (engine, version) only.
	// SP maps engine+version to OCI image (e.g. postgres+16 -> docker.io/library/postgres:16).
	Database DatabaseTierSpec `json:"database"`

	// Web Web tier. Uses OCI image.
	Web WebTierSpec `json:"web"`
}

// TierNetwork defines model for TierNetwork.
type TierNetwork struct {
	Ports *[]ContainerPort `json:"ports,omitempty"`
}

// WebTierSpec Web tier. Uses OCI image.
type WebTierSpec struct {
	// Image OCI image reference for the web server.
	Image   string       `json:"image"`
	Network *TierNetwork `json:"network,omitempty"`
}

// ListThreeTierAppsParams defines parameters for ListThreeTierApps.
type ListThreeTierAppsParams struct {
	MaxPageSize *int32  `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`
	PageToken   *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// CreateThreeTierAppParams defines parameters for CreateThreeTierApp.
type CreateThreeTierAppParams struct {
	// Id Optional app ID for idempotent creation
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// CreateThreeTierAppJSONRequestBody defines body for CreateThreeTierApp for application/json ContentType.
type CreateThreeTierAppJSONRequestBody = ThreeTierApp
